/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiEngineStatusRouteImport } from './routes/api/engine-status'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedAgentRouteImport } from './routes/_protected/agent'
import { Route as ApiPublicPollRouteImport } from './routes/api/public/poll'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEngineStatusRoute = ApiEngineStatusRouteImport.update({
  id: '/api/engine-status',
  path: '/api/engine-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAgentRoute = ProtectedAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiPublicPollRoute = ApiPublicPollRouteImport.update({
  id: '/api/public/poll',
  path: '/api/public/poll',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/agent': typeof ProtectedAgentRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/api/engine-status': typeof ApiEngineStatusRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/public/poll': typeof ApiPublicPollRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/agent': typeof ProtectedAgentRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/api/engine-status': typeof ApiEngineStatusRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/public/poll': typeof ApiPublicPollRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_protected/agent': typeof ProtectedAgentRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/api/engine-status': typeof ApiEngineStatusRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/public/poll': typeof ApiPublicPollRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/agent'
    | '/dashboard'
    | '/api/engine-status'
    | '/api/stats'
    | '/api/public/poll'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/agent'
    | '/dashboard'
    | '/api/engine-status'
    | '/api/stats'
    | '/api/public/poll'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/signup'
    | '/_protected/agent'
    | '/_protected/dashboard'
    | '/api/engine-status'
    | '/api/stats'
    | '/api/public/poll'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiEngineStatusRoute: typeof ApiEngineStatusRoute
  ApiStatsRoute: typeof ApiStatsRoute
  ApiPublicPollRoute: typeof ApiPublicPollRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/engine-status': {
      id: '/api/engine-status'
      path: '/api/engine-status'
      fullPath: '/api/engine-status'
      preLoaderRoute: typeof ApiEngineStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/agent': {
      id: '/_protected/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof ProtectedAgentRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/public/poll': {
      id: '/api/public/poll'
      path: '/api/public/poll'
      fullPath: '/api/public/poll'
      preLoaderRoute: typeof ApiPublicPollRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAgentRoute: typeof ProtectedAgentRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAgentRoute: ProtectedAgentRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiEngineStatusRoute: ApiEngineStatusRoute,
  ApiStatsRoute: ApiStatsRoute,
  ApiPublicPollRoute: ApiPublicPollRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
